const eventName = {
  ERROR: 'error',
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  READY_TO_JOIN: 'ready-to-join',
  JOINED: 'joined',
  COLOR_SELECTED: 'color-selected',
  SEND_MESSAGE: 'send-message',
  RECEIVE_MESSAGE: 'receive-message',
  YOU_JOINED: 'you-joined',
  NEW_USER_JOINED: 'new-user-joined',
  GAME_START: 'game-start',
  READY: 'ready',
  ADD_READY: 'add-ready',
  FIRST_DRAW: 'first-draw',
  DRAW_RESULT: 'draw-result',
  GUESS: 'guess',
  RESULT_GUESS: 'result-guess',
  NEXT_TURN: 'next-turn',
  NEXT_GAMEINFO: 'next-gameInfo',
  GAMEOVER: 'gameover',
  RESULT_SELECT: 'result-select',
  PLACE_JOKER: 'place-joker',
  SELECT_CARD_AS_SECURITY: 'select-card-as-security',
  ROOM_OUT: 'room-out',
  ONGOING: 'ongoing',
};
module.exports = { eventName };
